hmrc/telemetry-lambda-resources

README.md, {{cookiecutter.repository_name}}/.pre-commit-config.yaml, {{cookiecutter.repository_name}}/Dockerfile, {{cookiecutter.repository_name}}/buildspec.yml, {{cookiecutter.repository_name}}/buildspec_pr.yml, {{cookiecutter.repository_name}}/tools/check-tool-versions.sh, {{cookiecutter.repository_name}}/tox.ini
Co-authored-by: Stephen Palfreyman <18111914+sjpalf@users.noreply.github.com>
=> TEL-3093: Tweak templates to match aws-lambda-log-handler

{{cookiecutter.repository_name}}/setup.cfg
=> TEL-3093: add W503 skip check that conflicts with black re-formatter

cookiecutter.json, {{cookiecutter.repository_name}}/Makefile, {{cookiecutter.repository_name}}/bin/lambda-tools.sh
=> TEL-3093: allow setting of custom Makefile includes

{{cookiecutter.lambda_name_formatted}}/setup.cfg
=> TEL-3093: reduce test coverage

{{cookiecutter.lambda_name_formatted}}/Makefile, {{cookiecutter.lambda_name_formatted}}/setup.cfg
- TEL-3093: reduce test coverage
- TEL-3093: don't output new lines
=> TEL 3093 fix newlines

README.md
=> TEL-3093: update README.md

cookiecutter.json, {{cookiecutter.lambda_name_formatted}}/.bandit
=> TEL-3093: add ability to pass in bandit tests to skip

cookiecutter.json, {{cookiecutter.lambda_name_formatted}}/Dockerfile
=> TEL-3093: expose the lambda handler entrypoint as an input

cookiecutter.json, {{cookiecutter.lambda_name_formatted}}/bin/run-tests.sh
=> TEL-3093: run tests consistently using coverage

cookiecutter.json, {{cookiecutter.lambda_name_formatted}}/bin/run-tests.sh
=> TEL-3093: run tests using style parameter

README.md, cookiecutter.json, {{cookiecutter.lambda_name_formatted}}/bin/run-tests.sh
- TEL-3093: run tests using style parameter
- TEL-3093: fix jinja whitespace issues
=> TEL 3093 fix test script

{{cookiecutter.lambda_name_formatted}}/bin/run-tests.sh
=> TEL-3093: fix whitespace in jinja template

{{cookiecutter.lambda_name_formatted}}/Makefile
=> TEL-3093: disable poetry experimental installer

README.md
Co-authored-by: Rob White <Crumplepang@users.noreply.github.com>
=> TEL-3903: update README

cookiecutter.json, {{cookiecutter.lambda_name_formatted}}/setup.cfg
What did we do?
--
1. Added a variable to optionally append extra flake8 tests to ignore
=> TEL-3330 Allow a repo to add to the list of flake8 tests to ignore

{{cookiecutter.lambda_name_formatted}}/Makefile, {{cookiecutter.lambda_name_formatted}}/bin/lambda-tools.sh, {{cookiecutter.lambda_name_formatted}}/bin/package-lambda.sh
=> TEL-3383: refactor how package zip and hash work

{{cookiecutter.lambda_name_formatted}}/bin/lambda-tools.sh
=> TEL-3383: Fix unbound variable problem

{{cookiecutter.lambda_name_formatted}}/buildspec.yml
Co-authored-by: Tim Fothergill <67912934+TimothyFothergill@users.noreply.github.com>
=> TEL-3388: add missing env var from buildspec

{{cookiecutter.lambda_name_formatted}}/Makefile
=> TEL-2490 Fixup to prior commit

cookiecutter.json, {{cookiecutter.lambda_name_formatted}}/Makefile
Co-authored-by: Stephen Palfreyman <18111914+sjpalf@users.noreply.github.com>
=> TEL-3499: remove safety

{{cookiecutter.lambda_name_formatted}}/buildspec.yml
Co-authored-by: Lee Myring <29373851+thinkstack@users.noreply.github.com>
=> TEL-3702 - Remove unused Artifactory token

cookiecutter.json, {{cookiecutter.lambda_name_formatted}}/.python-version, {{cookiecutter.lambda_name_formatted}}/.tool-versions, {{cookiecutter.lambda_name_formatted}}/Dockerfile, {{cookiecutter.lambda_name_formatted}}/Makefile, {{cookiecutter.lambda_name_formatted}}/bin/entrypoint.sh, {{cookiecutter.lambda_name_formatted}}/bin/lambda-tools.sh, {{cookiecutter.lambda_name_formatted}}/bin/package-lambda.sh
- TEL-3758: remove artifactory remnants
- TEL-3758: add manylinux platform to pip install
- TEL-3758: expose python version as cookiecutter variables
=> TEL-3758 improve pip install to be more platform agnostic

cookiecutter.json
Co-authored-by: Jonny Heywood <60072280+jonnydh@users.noreply.github.com>
=> TEL-4654 Use Python 3.12.4 as default

cookiecutter.json
Reverts hmrc/telemetry-lambda-resources#52
Will park these changes until https://jira.tools.tax.service.gov.uk/browse/TEL-4464 is played
=> TEL-4654 Reverting to old version of Python pending TEL-4464

{{cookiecutter.lambda_name_formatted}}/.tool-versions
Co-authored-by: Damon Wright <150913287+wrightda101@users.noreply.github.com>
Co-authored-by: Gavin Davies <gavD@users.noreply.github.com>
=> TEL-4654 Add pre-commit to template
